// shaders.cpp
#include "shaders.h"

const std::string grid_vertex_shader_code =
    "#version 410 core\n"
    "\n"
    "layout (location = 0) in vec3 aPos;\n"
    "\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
    "}\n";

const std::string grid_fragment_shader_code =
    "#version 410 core\n"
    "\n"
    "uniform vec3 gridColor;\n"
    "uniform float alpha;\n"
    "\n"
    "out vec4 FragColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    FragColor = vec4(gridColor, alpha);\n"
    "}\n";

const std::string light_source_vertex_shader_code =
    "#version 330 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
    "} \n";

const std::string light_source_fragment_shader_code =
    "#version 330 core\n"
    "out vec4 FragColor;\n"
    "\n"
    "uniform vec3 lightColor;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    FragColor = vec4(lightColor, 1.0); \n"
    "}\n";

const std::string vertex_shader_code =
    "#version 330 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "layout (location = 1) in vec3 aNormal;\n"
    "layout (location = 2) in vec2 aTexCoords;\n"
    "\n"
    "out vec3 Normal;\n"
    "out vec3 FragPos;\n"
    "out vec2 TexCoords;\n"
    "\n"
    "uniform mat3 normal_model;\n"
    "\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "\n"
    "uniform float uv_rotation;\n"
    "float uniformAngle = 0.5f;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
    "    Normal = normal_model * aNormal; \n"
    "    FragPos = vec3(model * vec4(aPos, 1.0));\n"
    "    TexCoords = aTexCoords;\n"
    "} \n";

const std::string fragment_shader_code =
    "#version 330 core\n"
    "out vec4 FragColor;\n"
    "in vec3 FragPos;\n"
    "in vec3 Normal;\n"
    "in vec2 TexCoords;\n"
    "uniform float time;\n"
    "uniform vec3 viewPos;\n"
    "\n"
    "struct DirLight {\n"
    "    vec3 direction;\n"
    "\n"
    "    vec3 ambient;\n"
    "    vec3 diffuse;\n"
    "    vec3 specular;\n"
    "};\n"
    "#define MAX_DIR_LIGHTS 16\n"
    "uniform DirLight dirLights[MAX_DIR_LIGHTS];\n"
    "uniform int direct_lights;\n"
    "\n"
    "struct PointLight {\n"
    "    vec3 position;\n"
    "\n"
    "    float constant;\n"
    "    float linear;\n"
    "    float quadratic;\n"
    "\n"
    "    vec3 ambient;\n"
    "    vec3 diffuse;\n"
    "    vec3 specular;\n"
    "};\n"
    "#define MAX_POINT_LIGHTS 16\n"
    "uniform PointLight pointLights[MAX_POINT_LIGHTS];\n"
    "uniform int point_lights;\n"
    "\n"
    "struct SpotLight {\n"
    "    vec3 position;\n"
    "    vec3 direction;\n"
    "    float cutoff;\n"
    "    float outer_cutoff;\n"
    "\n"
    "    float constant;\n"
    "    float linear;\n"
    "    float quadratic;\n"
    "\n"
    "    vec3 ambient;\n"
    "    vec3 diffuse;\n"
    "    vec3 specular;\n"
    "};\n"
    "#define MAX_SPOT_LIGHTS 16\n"
    "uniform SpotLight spotLights[MAX_SPOT_LIGHTS];\n"
    "uniform int spot_lights;\n"
    "\n"
    "struct Texture {\n"
    "    sampler2D id;\n"
    "    int type;\n"
    "    float offsetX;\n"
    "    float offsetY;\n"
    "    float scaleX;\n"
    "    float scaleY;\n"
    "    float rotation;\n"
    "    float flipX;\n"
    "    float flipY;\n"
    "};\n"
    "#define MAX_TEXTURES 16\n"
    "uniform Texture textures[MAX_TEXTURES];\n"
    "uniform int num_textures;\n"
    "\n"
    "struct Material {\n"
    "    float ambient;\n"
    "    float diffuse;\n"
    "    float specular;\n"
    "\n"
    "    vec4 color;\n"
    "\n"
    "    float shininess;\n"
    "\n"
    "    float alpha;\n"
    "};\n"
    "uniform Material material;\n"
    "\n"
    "uniform vec4 highlight_color;\n"
    "uniform float highlight_value;\n"
    "uniform float pressValue;\n"
    "\n"
    "vec3 CalcDirLight(DirLight light, vec3 normal, vec3 viewDir);\n"
    "vec3 CalcPointLight(PointLight light, vec3 normal, vec3 fragPos, vec3 "
    "viewDir);\n"
    "vec3 CalcSpotLight(SpotLight light, vec3 normal, vec3 fragPos, vec3 "
    "viewDir);\n"
    "vec2 CalcTexCoords(Texture t, vec2 inTexCoords);\n"
    "\n"
    "vec3 g_normal_from_map = vec3(0.0);\n"
    "bool g_has_normal_map = false;\n"
    "float g_metallic = 0.0;\n"
    "float g_roughness = 0.5;\n"
    "float g_ao = 1.0;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec3 norm = normalize(Normal);\n"
    "    vec3 viewDir = normalize(viewPos - FragPos);\n"
    "    vec3 result = vec3(0.0);\n"
    "\n"
    "    for(int i=0; i<num_textures; i++){\n"
    "        vec2 mtc = CalcTexCoords(textures[i], TexCoords);\n"
    "        if(textures[i].type == 3){\n"
    "            vec3 nsamp = texture(textures[i].id, mtc).rgb * 2.0 - 1.0;\n"
    "            vec3 dpdx = dFdx(FragPos);\n"
    "            vec3 dpdy = dFdy(FragPos);\n"
    "            vec2 duvdx = dFdx(mtc);\n"
    "            vec2 duvdy = dFdy(mtc);\n"
    "            vec3 T = dpdx * duvdy.y - dpdy * duvdx.y;\n"
    "            vec3 B = dpdy * duvdx.x - dpdx * duvdy.x;\n"
    "            float invMax = inversesqrt(max(dot(T,T), dot(B,B)) + 1e-30);\n"
    "            T *= invMax;\n"
    "            B *= invMax;\n"
    "            T = normalize(T - dot(T, norm) * norm);\n"
    "            B = normalize(B - dot(B, norm) * norm - dot(B, T) * T);\n"
    "            mat3 TBN = mat3(T, B, norm);\n"
    "            g_normal_from_map = normalize(TBN * nsamp);\n"
    "            g_has_normal_map = true;\n"
    "        }\n"
    "        if(textures[i].type == 4)\n"
    "            g_metallic = texture(textures[i].id, mtc).r;\n"
    "        if(textures[i].type == 5)\n"
    "            g_roughness = texture(textures[i].id, mtc).r;\n"
    "        if(textures[i].type == 6)\n"
    "            g_ao = texture(textures[i].id, mtc).r;\n"
    "    }\n"
    "    if(g_has_normal_map) norm = g_normal_from_map;\n"
    "\n"
    "    for(int i = 0; i < direct_lights; i++)\n"
    "        result += CalcDirLight(dirLights[i], norm, viewDir);\n"
    "    for(int i = 0; i < point_lights; i++)\n"
    "        result += CalcPointLight(pointLights[i], norm, FragPos, "
    "viewDir);\n"
    "    for(int i = 0; i < spot_lights; i++)\n"
    "        result += CalcSpotLight(spotLights[i], norm, FragPos, viewDir);\n"
    "\n"
    "    for(int i=0; i<num_textures; i++){\n"
    "        vec2 tex_coords = CalcTexCoords(textures[i], TexCoords);\n"
    "        if(textures[i].type == 2){ \n"
    "            vec4 emission_texture = texture(textures[i].id, tex_coords);\n"
    "            if(emission_texture.a > 0.1)\n"
    "                result = vec3(emission_texture);\n"
    "        }\n"
    "    }\n"
    "\n"
    "    // Combine highlight with press value\n"
    "    vec3 finalColor = mix(result, vec3(highlight_color), max(pressValue, "
    "highlight_value)* highlight_color.a);\n"
    "    FragColor = vec4(finalColor, material.alpha);\n"
    "}\n"
    "\n"
    "vec2 CalcTexCoords(Texture t, vec2 inTexCoords){\n"
    "    vec2 tex_coords = inTexCoords;\n"
    "    tex_coords += vec2(-0.5, -0.5);\n"
    "    tex_coords /= vec2(t.scaleX, t.scaleY);\n"
    "    if (t.flipX > 0.5) tex_coords.x = -tex_coords.x;\n"
    "    if (t.flipY > 0.5) tex_coords.y = -tex_coords.y;\n"
    "    mat2 rot_mat = mat2(cos(t.rotation), sin(t.rotation), "
    "-sin(t.rotation), cos(t.rotation));\n"
    "    tex_coords *= rot_mat;\n"
    "    tex_coords += vec2(0.5, 0.5);\n"
    "    tex_coords += vec2(-t.offsetX, t.offsetY) * rot_mat;\n"
    "    return tex_coords;\n"
    "}\n"
    "\n"
    "vec3 CalcDirLight(DirLight light, vec3 normal, vec3 viewDir)\n"
    "{\n"
    "    vec3 lightDir = normalize(-light.direction);\n"
    "    float diff = max(dot(normal, lightDir), 0.0);\n"
    "    vec3 reflectDir = reflect(-lightDir, normal);\n"
    "    float roughShin = mix(material.shininess * 4.0, "
    "material.shininess * 0.2, g_roughness);\n"
    "    float spec = pow(max(dot(viewDir, reflectDir), 0.0), roughShin);\n"
    "    vec3 albedo = vec3(material.color);\n"
    "    vec3 ambient  = light.ambient * albedo;\n"
    "    vec3 diffuse  = light.diffuse * diff * albedo;\n"
    "    vec3 specular = light.specular * spec * material.specular;\n"
    "\n"
    "    for(int i=0; i<num_textures; i++){\n"
    "        vec2 tex_coords = CalcTexCoords(textures[i], TexCoords);\n"
    "        if(textures[i].type == 0){\n"
    "            vec4 diffuse_texture = texture(textures[i].id, tex_coords);\n"
    "            if(diffuse_texture.a > 0.1){\n"
    "                albedo = vec3(diffuse_texture);\n"
    "                ambient = light.ambient * albedo;\n"
    "                diffuse = light.diffuse * diff * albedo;\n"
    "                specular = light.specular * spec * material.specular;\n"
    "            }\n"
    "        }\n"
    "        if(textures[i].type == 1){\n"
    "            vec4 specular_texture = texture(textures[i].id, tex_coords);\n"
    "            if(specular_texture.a > 0.1)\n"
    "                specular = light.specular * spec * "
    "vec3(specular_texture);\n"
    "        }\n"
    "    }\n"
    "    ambient *= material.ambient * g_ao;\n"
    "    diffuse *= material.diffuse;\n"
    "    // Simplified metallic response (not a full Cook-Torrance BRDF -\n"
    "    // this app doesn't have per-vertex tangents or an IBL/energy-\n"
    "    // conserving pipeline to build one on top of): a real metal has\n"
    "    // no diffuse reflection at all and tints its specular by its own\n"
    "    // color rather than the light's, so this fades diffuse out and\n"
    "    // blends specular toward albedo-tinted as metallic increases.\n"
    "    specular = mix(specular, albedo * spec, g_metallic);\n"
    "    diffuse *= (1.0 - g_metallic);\n"
    "    return (ambient + diffuse + specular);\n"
    "}\n"
    "\n"
    "vec3 CalcPointLight(PointLight light, vec3 normal, vec3 fragPos, vec3 "
    "viewDir)\n"
    "{\n"
    "    vec3 lightDir = normalize(light.position - fragPos);\n"
    "    float diff = max(dot(normal, lightDir), 0.0);\n"
    "    vec3 reflectDir = reflect(-lightDir, normal);\n"
    "    float roughShin = mix(material.shininess * 4.0, "
    "material.shininess * 0.2, g_roughness);\n"
    "    float spec = pow(max(dot(viewDir, reflectDir), 0.0), roughShin);\n"
    "    float distance = length(light.position - fragPos);\n"
    "    float attenuation = 1.0 / (light.constant + light.linear * distance + "
    "light.quadratic * (distance * distance));\n"
    "    vec3 albedo = vec3(material.color);\n"
    "    vec3 ambient  = light.ambient  * albedo;\n"
    "    vec3 diffuse  = light.diffuse  * diff * albedo;\n"
    "    vec3 specular = light.specular * spec * material.specular;\n"
    "\n"
    "    for(int i=0; i<num_textures; i++){\n"
    "        vec2 tex_coords = CalcTexCoords(textures[i], TexCoords);\n"
    "        if(textures[i].type == 0){\n"
    "            vec4 diffuse_texture = texture(textures[i].id, tex_coords);\n"
    "            if(diffuse_texture.a > 0.1){\n"
    "                albedo = vec3(diffuse_texture);\n"
    "                ambient = light.ambient * albedo;\n"
    "                diffuse = light.diffuse * diff * albedo;\n"
    "                specular = light.specular * spec * material.specular;\n"
    "            }\n"
    "        }\n"
    "        if(textures[i].type == 1){\n"
    "            vec4 specular_texture = texture(textures[i].id, tex_coords);\n"
    "            if(specular_texture.a > 0.1)\n"
    "                specular = light.specular * spec * "
    "vec3(specular_texture);\n"
    "        }\n"
    "    }\n"
    "    ambient *= material.ambient * g_ao;\n"
    "    diffuse *= material.diffuse;\n"
    "    specular = mix(specular, albedo * spec, g_metallic);\n"
    "    diffuse *= (1.0 - g_metallic);\n"
    "    ambient  *= attenuation;\n"
    "    diffuse  *= attenuation;\n"
    "    specular *= attenuation;\n"
    "    return (ambient + diffuse + specular);\n"
    "}\n"
    "\n"
    "vec3 CalcSpotLight(SpotLight light, vec3 normal, vec3 fragPos, vec3 "
    "viewDir)\n"
    "{\n"
    "    vec3 lightDir = normalize(light.position - fragPos);\n"
    "    float diff = max(dot(normal, lightDir), 0.0);\n"
    "    vec3 reflectDir = reflect(-lightDir, normal);\n"
    "    float roughShin = mix(material.shininess * 4.0, "
    "material.shininess * 0.2, g_roughness);\n"
    "    float spec = pow(max(dot(viewDir, reflectDir), 0.0), roughShin);\n"
    "    float distance = length(light.position - fragPos);\n"
    "    float attenuation = 1.0 / (light.constant + light.linear * distance + "
    "light.quadratic * (distance * distance));\n"
    "    vec3 albedo = vec3(material.color);\n"
    "    vec3 ambient  = light.ambient  * albedo;\n"
    "    vec3 diffuse  = light.diffuse  * diff * albedo;\n"
    "    vec3 specular = light.specular * spec * material.specular;\n"
    "\n"
    "    for(int i=0; i<num_textures; i++){\n"
    "        vec2 tex_coords = CalcTexCoords(textures[i], TexCoords);\n"
    "        if(textures[i].type == 0){\n"
    "            vec4 diffuse_texture = texture(textures[i].id, tex_coords);\n"
    "            if(diffuse_texture.a > 0.1){\n"
    "                albedo = vec3(diffuse_texture);\n"
    "                ambient = light.ambient * albedo;\n"
    "                diffuse = light.diffuse * diff * albedo;\n"
    "                specular = light.specular * spec * material.specular;\n"
    "            }\n"
    "        }\n"
    "        if(textures[i].type == 1){\n"
    "            vec4 specular_texture = texture(textures[i].id, tex_coords);\n"
    "            if(specular_texture.a > 0.1)\n"
    "                specular = light.specular * spec * "
    "vec3(specular_texture);\n"
    "        }\n"
    "    }\n"
    "    specular = mix(specular, albedo * spec, g_metallic);\n"
    "    diffuse *= (1.0 - g_metallic);\n"
    "    ambient  *= attenuation * g_ao;\n"
    "    diffuse  *= attenuation;\n"
    "    specular *= attenuation;\n"
    "    float theta = dot(lightDir, normalize(-light.direction));\n"
    "    float epsilon = light.cutoff - light.outer_cutoff;\n"
    "    float intensity = clamp((theta - light.outer_cutoff) / epsilon, 0.0, "
    "1.0);\n"
    "    diffuse *= intensity;\n"
    "    specular *= intensity;\n"
    "    vec3 result = ambient;\n"
    "    if(theta > light.outer_cutoff)\n"
    "        result += diffuse + specular;\n"
    "    return result;\n"
    "}\n";

const std::string touch_area_vertex_shader_code =
    "#version 330 core\n"
    "layout (location = 0) in vec3 aPos;\n"
    "uniform mat4 model;\n"
    "uniform mat4 view;\n"
    "uniform mat4 projection;\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * view * model * vec4(aPos, 1.0);\n"
    "}\n";

const std::string touch_area_fragment_shader_code =
    "#version 330 core\n"
    "out vec4 FragColor;\n"
    "uniform vec3 lightColor;\n"
    "void main()\n"
    "{\n"
    "    FragColor = vec4(lightColor, 1.0);\n"
    "}\n";

// ------------------------------------------------------------------
// Text shaders for overlay
// ------------------------------------------------------------------
const std::string text_vertex_shader_code =
    "#version 330 core\n"
    "layout (location = 0) in vec2 aPos;\n"
    "layout (location = 1) in vec2 aTexCoords;\n"
    "out vec2 TexCoords;\n"
    "uniform mat4 projection;\n"
    "void main()\n"
    "{\n"
    "    gl_Position = projection * vec4(aPos, 0.0, 1.0);\n"
    "    TexCoords = aTexCoords;\n"
    "}\n";

const std::string text_fragment_shader_code =
    "#version 330 core\n"
    "in vec2 TexCoords;\n"
    "uniform sampler2D fontTexture;\n"
    "uniform vec3 textColor;\n"
    "out vec4 FragColor;\n"
    "void main()\n"
    "{\n"
    "    float alpha = texture(fontTexture, TexCoords).r;\n"
    "    if(alpha < 0.1) discard;\n"
    "    FragColor = vec4(textColor, alpha);\n"
    "}\n";