# Script-mode helper (cmake -P) that works out this build's version and
# writes the generated files that carry it into the app. Run once at
# configure time and again on every build (see the app_version target
# in the root CMakeLists.txt), so a new tag or commit is picked up
# without needing to re-run CMake by hand.
#
# Inputs (-D on the command line):
#   SRC_DIR          - repository root
#   OUT_DIR          - where generated files go (the build tree)
#   VERSION_OVERRIDE - optional explicit version, e.g. "v1.3.4"
#
# Version source, first one that yields something:
#   1. VERSION_OVERRIDE (the APP_VERSION cache variable)
#   2. the APP_VERSION environment variable - how CI passes the tag into
#      the Docker builds, which don't get a .git directory (.dockerignore)
#   3. `git describe --tags` - local builds from a clone
#   4. "0.0.0-dev"
#
# Outputs (each only rewritten when its content actually changes, so an
# unchanged version never triggers a rebuild):
#   app_version.h        - APP_VERSION_* macros
#   release_notes_data.h - release-notes/v<X.Y.Z>.md embedded as a string
#   app_version.rc       - Windows icon + VERSIONINFO (file Properties)
#   app_version.txt      - plain X.Y.Z, read by the macOS Info.plist step

set(ver "${VERSION_OVERRIDE}")
if(ver STREQUAL "" AND DEFINED ENV{APP_VERSION})
  set(ver "$ENV{APP_VERSION}")
endif()
if(ver STREQUAL "")
  find_program(GIT_EXE git)
  if(GIT_EXE AND EXISTS "${SRC_DIR}/.git")
    execute_process(
      COMMAND "${GIT_EXE}" describe --tags --match "v[0-9]*"
      WORKING_DIRECTORY "${SRC_DIR}"
      OUTPUT_VARIABLE ver
      RESULT_VARIABLE git_rc
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)
    if(NOT git_rc EQUAL 0)
      set(ver "")
    endif()
  endif()
endif()
if(ver STREQUAL "")
  set(ver "0.0.0-dev")
endif()

string(REGEX REPLACE "^[vV]" "" ver "${ver}")
if(ver MATCHES "^([0-9]+)\\.([0-9]+)\\.([0-9]+)")
  set(ver_major "${CMAKE_MATCH_1}")
  set(ver_minor "${CMAKE_MATCH_2}")
  set(ver_patch "${CMAKE_MATCH_3}")
else()
  # Anything that isn't X.Y.Z-shaped (a branch name, say) is a dev build.
  set(ver_major 0)
  set(ver_minor 0)
  set(ver_patch 0)
  set(ver "0.0.0-${ver}")
endif()
set(ver_base "${ver_major}.${ver_minor}.${ver_patch}")

file(MAKE_DIRECTORY "${OUT_DIR}")

function(write_if_changed path content)
  if(EXISTS "${path}")
    file(READ "${path}" old)
    if(old STREQUAL content)
      return()
    endif()
  endif()
  file(WRITE "${path}" "${content}")
endfunction()

# ---- app_version.h ----
write_if_changed("${OUT_DIR}/app_version.h" "// Generated by cmake/GenerateVersion.cmake - do not edit
#pragma once
// Full version as shown to the user, e.g. \"1.3.4\" for a tagged
// release or \"1.3.4-2-gabc1234\" for a build two commits past it.
#define APP_VERSION_STRING \"${ver}\"
// Just X.Y.Z - what update checks and \"What's New\" compare against.
#define APP_VERSION_BASE \"${ver_base}\"
#define APP_VERSION_MAJOR ${ver_major}
#define APP_VERSION_MINOR ${ver_minor}
#define APP_VERSION_PATCH ${ver_patch}
")

# ---- release_notes_data.h ----
# Embedded as bytes rather than a string literal so quotes, backslashes
# and non-ASCII characters in the notes need no escaping at all.
set(notes_file "${SRC_DIR}/release-notes/v${ver_base}.md")
set(notes_bytes "")
if(EXISTS "${notes_file}")
  file(READ "${notes_file}" notes_hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," notes_bytes "${notes_hex}")
endif()
write_if_changed("${OUT_DIR}/release_notes_data.h" "// Generated by cmake/GenerateVersion.cmake from release-notes/v${ver_base}.md - do not edit
#pragma once
// Empty (just the terminator) when no notes file exists for this version.
static const unsigned char kEmbeddedReleaseNotesBytes[] = {${notes_bytes}0x00};
static const char *const kEmbeddedReleaseNotes =
    reinterpret_cast<const char *>(kEmbeddedReleaseNotesBytes);
")

# ---- app_version.rc (Windows only, harmless elsewhere) ----
write_if_changed("${OUT_DIR}/app_version.rc" "// Generated by cmake/GenerateVersion.cmake - do not edit
#include <winver.h>

IDI_ICON1 ICON \"${SRC_DIR}/packaging/windows/icon.ico\"

VS_VERSION_INFO VERSIONINFO
FILEVERSION ${ver_major},${ver_minor},${ver_patch},0
PRODUCTVERSION ${ver_major},${ver_minor},${ver_patch},0
FILEFLAGSMASK 0x3fL
FILEFLAGS 0x0L
FILEOS VOS_NT_WINDOWS32
FILETYPE VFT_APP
FILESUBTYPE VFT2_UNKNOWN
BEGIN
    BLOCK \"StringFileInfo\"
    BEGIN
        BLOCK \"040904b0\"
        BEGIN
            VALUE \"CompanyName\", \"Khyretos\"
            VALUE \"FileDescription\", \"3D Controller Overlay +\"
            VALUE \"FileVersion\", \"${ver}\"
            VALUE \"InternalName\", \"3dco+\"
            VALUE \"OriginalFilename\", \"3dco+.exe\"
            VALUE \"ProductName\", \"3D Controller Overlay +\"
            VALUE \"ProductVersion\", \"${ver}\"
        END
    END
    BLOCK \"VarFileInfo\"
    BEGIN
        VALUE \"Translation\", 0x409, 1200
    END
END
")

# ---- app_version.txt ----
write_if_changed("${OUT_DIR}/app_version.txt" "${ver_base}\n")
